//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Annex()
        {
            this.BranchGroup = new HashSet<BranchGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FormalName { get; set; }
        public string TableName { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchGroup> BranchGroup { get; set; }
    }
}
