//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnexVsBranchGroup
    {
        public int Id { get; set; }
        public int AnnexId { get; set; }
        public System.Guid BranchGroupUid { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Annex Annex { get; set; }
        public virtual BranchGroup BranchGroup { get; set; }
    }
}
