//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class APF
    {
        public System.Guid BranchGroupSchemeUid { get; set; }
        public int PreFaultConditionsId { get; set; }
        public string PowerFlowStandardValue { get; set; }
        public string PowerFlowStandardDescription { get; set; }
        public string PowerFlowSafeValue { get; set; }
        public string PowerFlowSafeDescription { get; set; }
        public string PowerFlowEmergencyValue { get; set; }
        public string PowerFlowEmergencyDescription { get; set; }
        public string ControlledPowerFlowStandard { get; set; }
        public string ControlledPowerFlowSafe { get; set; }
        public string ControlledPowerFlowEmergency { get; set; }
        public string PowerFlowForcedStateValue { get; set; }
        public string PowerFlowForcedStateDescription { get; set; }
        public string PowerFlowStandardValueHandWritten { get; set; }
        public string PowerFlowStandardDescriptionHandWritten { get; set; }
        public string PowerFlowSafeValueHandWritten { get; set; }
        public string PowerFlowSafeDescriptionHandWritten { get; set; }
        public string PowerFlowEmergencyValueHandWritten { get; set; }
        public string PowerFlowEmergencyDescriptionHandWritten { get; set; }
        public string PowerFlowForcedStateValueHandWritten { get; set; }
        public string PowerFlowForcedStateDescriptionHandWritten { get; set; }
    
        public virtual PreFaultConditions PreFaultConditions { get; set; }
    }
}
