//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class APNU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APNU()
        {
            this.PostFaultConditions = new HashSet<PostFaultConditions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FormalName { get; set; }
        public Nullable<double> PowerFlowSetting { get; set; }
        public Nullable<double> StaticsCoefficient { get; set; }
        public Nullable<double> DynamicsCoefficient { get; set; }
        public Nullable<double> CurrentCoefficient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostFaultConditions> PostFaultConditions { get; set; }
    }
}
