//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchGroup()
        {
            this.BranchGroupScheme = new HashSet<BranchGroupScheme>();
        }
    
        public System.Guid Uid { get; set; }
        public Nullable<int> AnnexId { get; set; }
        public Nullable<int> Number { get; set; }
        public string Name { get; set; }
        public string CorrectionFactorName { get; set; }
        public Nullable<double> CorrectionFactorMinValue { get; set; }
        public Nullable<double> CorrectionFactorMaxValue { get; set; }
        public string Note { get; set; }
    
        public virtual Annex Annex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchGroupScheme> BranchGroupScheme { get; set; }
    }
}
