//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchGroupVsBranchGroupScheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchGroupVsBranchGroupScheme()
        {
            this.PreFaultConditions = new HashSet<PreFaultConditions>();
        }
    
        public int Id { get; set; }
        public System.Guid BranchGroupUid { get; set; }
        public System.Guid BranchGroupSchemeUid { get; set; }
        public bool IsActive { get; set; }
        public string Note { get; set; }
    
        public virtual BranchGroup BranchGroup { get; set; }
        public virtual BranchGroupScheme BranchGroupScheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFaultConditions> PreFaultConditions { get; set; }
    }
}
