//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchGroupScheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchGroupScheme()
        {
            this.PreFaultConditions = new HashSet<PreFaultConditions>();
        }
    
        public System.Guid Uid { get; set; }
        public Nullable<System.Guid> BranchGroupUid { get; set; }
        public Nullable<int> Number { get; set; }
        public string Name { get; set; }
    
        public virtual BranchGroup BranchGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFaultConditions> PreFaultConditions { get; set; }
    }
}
