//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentVsInfluencingEquipment
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public System.Guid InfluencingEquipmentUid { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual InfluencingEquipment InfluencingEquipment { get; set; }
    }
}
