//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Management
    {
        public int Id { get; set; }
        public Nullable<int> ManagementTasksId { get; set; }
        public Nullable<bool> Using { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public Nullable<int> Priority { get; set; }
    
        public virtual ManagementTasks ManagementTasks { get; set; }
    }
}
