//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreFaultConditions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreFaultConditions()
        {
            this.PostFaultConditions = new HashSet<PostFaultConditions>();
        }
    
        public System.Guid BranchGroupSchemeUid { get; set; }
        public int Id { get; set; }
        public Nullable<int> BoundingElementsId { get; set; }
        public Nullable<int> InfluencingEquipmentId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> TemperatureId { get; set; }
        public Nullable<bool> UsingRow { get; set; }
        public Nullable<double> LimitPowerFlow { get; set; }
        public Nullable<double> TprPowerFlow { get; set; }
        public Nullable<double> EprPowerFlow { get; set; }
        public Nullable<double> CurrentPowerFlow { get; set; }
        public Nullable<double> VoltagePowerFlow { get; set; }
        public Nullable<int> IrOscExpressions { get; set; }
        public string Comment { get; set; }
    
        public virtual APF APF { get; set; }
        public virtual BoundingElements BoundingElements { get; set; }
        public virtual BranchGroupScheme BranchGroupScheme { get; set; }
        public virtual InfluencingEquipment InfluencingEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostFaultConditions> PostFaultConditions { get; set; }
        public virtual Seasons Seasons { get; set; }
        public virtual Temperature Temperature { get; set; }
    }
}
